# Generated by Django 3.2.5 on 2021-09-10 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_review_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rated',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
    ]
