# Generated by Django 3.2.5 on 2021-09-11 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_review_rated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='description',
        ),
        migrations.RemoveField(
            model_name='review',
            name='title',
        ),
        migrations.AddField(
            model_name='review',
            name='review',
            field=models.TextField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name='review',
            name='rated',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
    ]
