# Generated by Django 3.2.5 on 2021-09-15 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_starchart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StarChart',
        ),
    ]
