# Generated by Django 3.2.5 on 2021-09-17 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_delete_starchart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='likes',
        ),
    ]
